version: '3'

services:
  db:
    container_name: db
    build: ./db
    ports:
      - 5435:5432
    env_file:
      - dev.env
    healthcheck:
      test: exit 0

  api:
    container_name: api
    build: .
    volumes:
      - '.:/usr/src'
    ports:
      - 5001:5000
    env_file:
      - dev.env
    depends_on:
      - db

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 9000:9000
    env_file:
      - dev.env
    depends_on:
      - api

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - client
