version: '3'

services:
  db:
    container_name: db
    build: ./db
    ports:
      - 5435:5432
    env_file:
      - dev.env
    healthcheck:
      test: exit 0

  web:
    container_name: web
    build: .
    volumes:
      - '.:/usr/src'
    ports:
      - 5001:5000
    env_file:
      - dev.env
    depends_on:
      - db
